# docker postgresql confiq
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: app
  username: appuser
  password: password
  host: db
  # database: <%= ENV['DB_NAME'] %>
  # username: <%= ENV['DB_USER'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
  # host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  # database: noteapp_development

test:
  <<: *default
  # database: noteapp_test

production:
  <<: *default
